### ISSUE TITLE
Return Result<T> instead of panicking

### ISSUE THREAD

**Issue by kuon** [sphinxc0re/rust-base24#1]
In the java version, I throw exceptions when the input has the wrong length or if invalid characters are present in the string to be decoded. But exceptions are normal error handling in Java but not in rust.

I suggest that encode and decode functions return Result types instead, for easier error handling in a rust way.

**Comment by sphinxc0re** [comment]
Sure. This project is a really rough draft of what has to follow. I will eventually add proper error handling using `thiserror`

**Comment by sphinxc0re** [comment]
Fixed in 4b99922aa896d920359a2127acd4be32be148a60
